### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Hypercubed**
Spelling and grammar.

### CODE REVIEW

**Comment by rreusser** [comment]
Thanks! Only caveat is that I've been doing this thing where `README.mdtex` gets compiled into `README.md` so that I can toss in the LaTeX equations. It's experimental and has a few issues, but it's clear that if I'm going to use it, I should really be throwing a brief explanation block into the READMEs and probably an html comment in `REAMDE.md` that makes it clear it's `README.mdtex` that needs to be modified. The procedure is (assuming latex is installed, which is a pain in the butt if not so I was thinking of falling back on a service like http://tex.la/):

```
gulp mdtex
```

I've made the changes you noted and have deployed that so will close this PR, but I appreciate it and any other feedback you might have! Next up is a RK-5(4) adaptive timestepping integrator…

**Comment by rreusser** [comment]
Specifically, this: https://github.com/rreusser/gulp-markdown-equations

**Comment by Hypercubed** [comment]
NP.  Sorry, I didn't notice your build step.  In fact I was using this module in a plunker via https://wzrd.in/ so I never even really cloned the repo.  This module works well (http://plnkr.co/edit/6BeD5a) but, as a matter of fact, I need adaptive timestepping!!!

**Comment by rreusser** [comment]
Very cool! Hard to view on mobile but glad to know it's useful. Will try to get basic adaptive up and running in the next couple days!

**Comment by rreusser** [comment]
@Hypercubed — I created another module: [ode-rk45-cash-karp](https://github.com/scijs/ode-rk45-cash-karp) that does adaptive timestepping.

I've tested it fairly carefully, but I can't promise there aren't loopholes or bugs. The only remaining feature I need to add is clipping the timestep so that you can integrate adaptively up to some predefined point. Otherwise the API is exactly identical so you can probably just swap one out for the other. The only exception—not yet documented—is that it accepts options:

`rk45(  y0, deriv, t0, dt, {tol: 1e-8, maxIncreaseFactor: 10, maxDecreaseFactor: 10, dtMin: 0} )`
- `tol`: adaptive tolerance to be met
- `maxIncreaseFactor`: maximum amount by which to increase the timestep
- `maxDecreaseFactor`: maximum amount by which to decrease the timestep
- `dtMin`: throws an error but computes anyway if timestep gets smaller than this limit

Otherwise, again, it's pretty much swappable. Like twenty more minutes to finish this off, I think, but gotta go!

**Comment by Hypercubed** [comment]
I'll give it a try in a few days.  One thing I noticed is that I will probbally need to override the `_error` function.

**Comment by rreusser** [comment]
Cool. Yeah, I'm not 100% sure about big pieces of this. Can you elaborate on how it could be improved?

**Comment by rreusser** [comment]
In particular, I was thinking about allowing manual scaling of error in each dimension, but I'm not experienced enough in general-purpose numerical libraries to know precisely how to manage tolerances. For starters though, I can split up the function into one function that simply calculates the error and another that translates that into a single metric.

**Comment by rreusser** [comment]
@Hypercubed — not to get carried away here, but I've abstracted out and documented what seem like the questionable parts and added some features and more testing. The error computation should be mostly configurable now without getting too far into the internals. Let me know if you have further thoughts/needs, otherwise take care, enjoy, and I hope it's useful!

**Comment by Hypercubed** [comment]
It will likely be a few days before I have a chance to look at the new lib.  What I will likely have is a mass balance equation that I would use to calulate the error.

**Comment by rreusser** [comment]
Ah, then you're in luck. Let me know if you need an API change, but should basically be a one-liner with the added configuration options.

**Pull request closed without merging**
